---
resources:
  - name: concourse_cypress
    type: git
    source:
      uri: https://github.com/EdmundHusserl/concourse_cypress.git
      branch: master

jobs:
  - name: cypress
    public: true
    plan:
      - get: concourse_cypress
      - task: run_tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: cypress/base}
          inputs:
            - name: concourse_cypress
          run:
            path: /bin/bash
            args: 
              - -exc
              - |
                cd concourse_cypress
                npm i
                npx cypress run --browser chrome